# Generated by Django 5.0.6 on 2024-05-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0002_znacky_remove_autamodel_znacka_alter_autamodel_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Znacky',
        ),
        migrations.AlterField(
            model_name='autamodel',
            name='datumPridani',
            field=models.DateField(),
        ),
    ]
