# Generated by Django 5.0.6 on 2024-05-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auta", "0008_alter_autamodel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autamodel",
            name="id",
            field=models.UUIDField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
