# Generated by Django 5.0.6 on 2024-05-20 10:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auta", "0009_alter_autamodel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autamodel",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
