# Generated by Django 5.0.6 on 2024-05-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0010_alter_autamodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autamodel',
            name='odkazOblazku',
        ),
        migrations.AddField(
            model_name='autamodel',
            name='autoOblazek',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
