# Generated by Django 5.0.6 on 2024-05-20 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auta", "0012_zakaznik_remove_autamodel_rok_autamodel_vypujceno_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="autamodel",
            name="datumPridani",
        ),
    ]
