# Generated by Django 5.0.6 on 2024-05-20 19:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0013_remove_autamodel_datumpridani'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vypujcka',
            name='id',
        ),
        migrations.AlterField(
            model_name='vypujcka',
            name='idVypujcky',
            field=models.UUIDField(default='', primary_key=True, serialize=False, unique=True, verbose_name=uuid.uuid4),
        ),
    ]
