# Generated by Django 5.0.6 on 2024-05-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0016_vypujcka_ukonceno_alter_vypujcka_stavtachkonec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vypujcka',
            name='idVypujcky',
            field=models.UUIDField(default='uuid.uuid4', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
